/********************************************************************************
** Form generated from reading UI file 'mywidget.ui'
**
** Created: Mon Jun 4 16:03:25 2018
**      by: Qt User Interface Compiler version 4.8.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MYWIDGET_H
#define UI_MYWIDGET_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QHeaderView>
#include <QtGui/QLCDNumber>
#include <QtGui/QLabel>
#include <QtGui/QPushButton>
#include <QtGui/QScrollArea>
#include <QtGui/QStackedWidget>
#include <QtGui/QTabWidget>
#include <QtGui/QVBoxLayout>
#include <QtGui/QWidget>
#include <myprogressbar.h>
#include "engtach.h"
#include "mqlabel.h"
#include "mydashboard.h"
#include "softkeylineedit.h"

QT_BEGIN_NAMESPACE

class Ui_myWidget
{
public:
    QTabWidget *tabWidget;
    QWidget *tab_8;
    myDashboard *widget_eng;
    MQlabel *eng_chg;
    MQlabel *l_preheat;
    QLabel *eng_gear;
    MQlabel *eng_hb;
    MQlabel *l_turn_lf;
    MQlabel *l_turn_rt;
    Engtach *widget_Tach;
    MQlabel *l_highlight;
    MQlabel *l_eng_fault;
    MQlabel *l_full;
    QLabel *l_clutch_st;
    QLabel *l_indt_lm;
    MQlabel *l_air_cln;
    MQlabel *l_oil_water;
    QScrollArea *scrollArea_11;
    QWidget *scrollAreaWidgetContents_11;
    MQlabel *w_elevator;
    QLabel *label_62;
    QLabel *label_34;
    QLabel *label_8;
    QLabel *l_dtfan_sp;
    MQlabel *w_rollerspeed;
    QLabel *re_thr_sp;
    MQlabel *w_re_thr_sp;
    MQlabel *w_cut_mach;
    QLabel *label_63;
    QLabel *label_31;
    QLabel *l_fdaugersp;
    QLabel *label_27;
    QLabel *l_reedspeed;
    MQlabel *w_fdaugersp;
    QLabel *l_rollerspeed;
    QLabel *cut_mach;
    MQlabel *w_dtfan_sp;
    QLabel *l_elevator;
    QLabel *label_9;
    MQlabel *w_reed_speed;
    QLabel *label;
    QLabel *label_3;
    QLabel *label_4;
    QLabel *label_5;
    QLabel *label_10;
    QLabel *label_14;
    QLabel *label_15;
    QScrollArea *scrollArea_12;
    QWidget *scrollAreaWidgetContents_12;
    QLabel *label_46;
    QLabel *dr_fan_impr_rate;
    QLabel *dr_fan_rate;
    QLabel *l_crushrate;
    QLabel *label_107;
    QLabel *label_106;
    QLabel *label_111;
    QLabel *drift_lose_rate;
    QLabel *impr_rate;
    QLabel *label_23;
    QLabel *label_29;
    QLabel *label_32;
    QLabel *label_41;
    QLabel *label_102;
    QLabel *label_88;
    QLabel *label_65;
    QScrollArea *scrollArea_13;
    QWidget *scrollAreaWidgetContents_13;
    QLabel *totle_km;
    QLabel *totle_tm;
    QLabel *totle_m;
    QLabel *label_49;
    QLabel *label_51;
    QLabel *label_52;
    MQlabel *l_diplight;
    QScrollArea *scrollArea_10;
    QWidget *scrollAreaWidgetContents_10;
    QLabel *label_21;
    myProgressBar *w_eopres;
    QLabel *label_20;
    QScrollArea *scrollArea_14;
    QWidget *scrollAreaWidgetContents_14;
    QLabel *l_eng_them;
    QLabel *l_eng_sm;
    QLabel *label_16;
    QLabel *label_7;
    QLabel *label_19;
    QLabel *label_22;
    QLabel *l_voltage;
    QLabel *l_unloader;
    QWidget *tab;
    QScrollArea *scrollArea;
    QWidget *scrollAreaWidgetContents;
    QLabel *label_96;
    QLabel *label_28;
    QLabel *label_59;
    QLabel *profiling_height;
    QLabel *label_95;
    QLabel *reel_height;
    QLabel *label_68;
    QLabel *reel_shift;
    QLabel *label_25;
    QLabel *label_43;
    QLabel *label_92;
    QLabel *label_93;
    QLabel *label_94;
    QLabel *label_97;
    QLabel *label_98;
    QScrollArea *scrollArea_2;
    QWidget *scrollAreaWidgetContents_2;
    QLabel *roller_torque;
    QLabel *l_fan_angle;
    QLabel *label_54;
    QLabel *front_motor_sp;
    QLabel *rear_motor_sp;
    QWidget *layoutWidget;
    QVBoxLayout *verticalLayout_3;
    QLabel *label_64;
    QLabel *label_66;
    QLabel *label_67;
    QLabel *label_44;
    QLabel *label_50;
    MQlabel *w_front_motor_sp;
    MQlabel *w_rear_motor_sp;
    QLabel *label_83;
    QLabel *label_84;
    QLabel *label_86;
    QLabel *label_87;
    QLabel *label_89;
    QScrollArea *scrollArea_3;
    QWidget *scrollAreaWidgetContents_3;
    QLabel *label_61;
    QLabel *label_56;
    QLabel *label_18;
    QLabel *label_60;
    QLabel *label_40;
    QLabel *label_17;
    QLabel *label_58;
    QLabel *label_24;
    QLabel *label_38;
    QLabel *l_concavecl;
    QLabel *label_57;
    QLabel *label_30;
    QLabel *label_73;
    QLabel *label_74;
    QLabel *label_77;
    QLabel *label_78;
    QLabel *label_79;
    QLabel *label_80;
    QScrollArea *scrollArea_4;
    QWidget *scrollAreaWidgetContents_4;
    QLabel *weight_wet;
    QLabel *label_36;
    QLabel *weight_dry;
    QLabel *label_37;
    QLabel *label_81;
    QLabel *label_82;
    QScrollArea *scrollArea_5;
    QWidget *scrollAreaWidgetContents_5;
    QLabel *water_rate;
    QLabel *label_55;
    QLabel *grain_quality_monitor;
    QLabel *label_26;
    QLabel *label_100;
    QLabel *label_101;
    QScrollArea *scrollArea_6;
    QWidget *scrollAreaWidgetContents_6;
    QLabel *label_99;
    QLabel *label_85;
    QLabel *label_42;
    QLabel *label_69;
    QLabel *label_90;
    QLabel *label_91;
    QPushButton *control_set;
    QPushButton *parameter_set;
    QPushButton *parameter_set_2;
    QLabel *label_47;
    QLabel *label_48;
    QLabel *label_112;
    QWidget *tab_2;
    QScrollArea *scrollArea_7;
    QWidget *scrollAreaWidgetContents_8;
    QLabel *l_cuthei_down;
    QLabel *l_reelval_down;
    QLabel *l_reel_down;
    QLabel *l_clusterval_off;
    QLabel *s_minus;
    QLabel *l_cluster_off;
    QLabel *s_plus;
    QLabel *l_clusterval_on;
    QLabel *l_unswout;
    QLabel *l_unswin;
    QLabel *l_reelval_up;
    QLabel *s_fan;
    QLabel *l_reel_up;
    QLabel *l_unswinval;
    QLabel *l_cuthei_up;
    QLabel *l_unswoutval;
    QLabel *l_rolval_down;
    QLabel *l_cutheival_down;
    QLabel *l_cutheival_up;
    QLabel *l_rolval_up;
    QLabel *l_cluster_on;
    QLabel *l_rol_down;
    QLabel *l_rol_up;
    QLabel *l_backupdri;
    QScrollArea *scrollArea_8;
    QWidget *scrollAreaWidgetContents_7;
    MQlabel *l_rls_3;
    MQlabel *l_fm_2;
    QLabel *label_45;
    MQlabel *l_fas_3;
    QLabel *label_76;
    QLabel *label_71;
    MQlabel *l_rm_1;
    MQlabel *l_es_3;
    MQlabel *l_fm_3;
    MQlabel *l_es_1;
    MQlabel *l_fcm_2;
    MQlabel *l_fas_1;
    MQlabel *l_fas_2;
    MQlabel *l_rm_2;
    MQlabel *l_rls_1;
    QLabel *label_35;
    MQlabel *l_df_3;
    QLabel *label_39;
    QLabel *label_13;
    QLabel *label_75;
    MQlabel *l_cm_2;
    QLabel *label_72;
    MQlabel *l_df_1;
    MQlabel *l_rls_2;
    MQlabel *l_fcm_3;
    MQlabel *l_cm_3;
    QLabel *label_70;
    MQlabel *l_fcm_1;
    QLabel *label_11;
    QLabel *label_12;
    MQlabel *l_cm_1;
    MQlabel *l_df_2;
    MQlabel *l_rm_3;
    MQlabel *l_es_2;
    MQlabel *l_fm_1;
    QLabel *label_33;
    MQlabel *l_fd_2;
    MQlabel *l_fd_3;
    MQlabel *l_fd_1;
    QWidget *tab_3;
    QLCDNumber *lcdNumber;
    QPushButton *exit;
    QStackedWidget *syssw;
    QWidget *page;
    QPushButton *sbtn;
    QPushButton *out_btn;
    QLabel *label_2;
    SoftKeyLineEdit *uname;
    SoftKeyLineEdit *upassword;
    QLabel *label_6;

    void setupUi(QWidget *myWidget)
    {
        if (myWidget->objectName().isEmpty())
            myWidget->setObjectName(QString::fromUtf8("myWidget"));
        myWidget->resize(800, 450);
        QIcon icon;
        icon.addFile(QString::fromUtf8(":/images/leiwo.png"), QSize(), QIcon::Normal, QIcon::Off);
        myWidget->setWindowIcon(icon);
        myWidget->setLayoutDirection(Qt::LeftToRight);
        myWidget->setStyleSheet(QString::fromUtf8(""));
        tabWidget = new QTabWidget(myWidget);
        tabWidget->setObjectName(QString::fromUtf8("tabWidget"));
        tabWidget->setGeometry(QRect(0, 0, 802, 455));
        QFont font;
        font.setFamily(QString::fromUtf8("AR PL UKai CN"));
        font.setPointSize(22);
        font.setBold(false);
        font.setItalic(false);
        font.setWeight(50);
        font.setKerning(false);
        tabWidget->setFont(font);
        tabWidget->setContextMenuPolicy(Qt::DefaultContextMenu);
        tabWidget->setLayoutDirection(Qt::LeftToRight);
        tabWidget->setAutoFillBackground(false);
        tabWidget->setStyleSheet(QString::fromUtf8("font: 22pt \"AR PL UKai CN\";\n"
"background-color: rgb(222, 248, 249);"));
        tabWidget->setTabPosition(QTabWidget::South);
        tabWidget->setTabShape(QTabWidget::Triangular);
        tabWidget->setIconSize(QSize(40, 40));
        tabWidget->setTabsClosable(false);
        tab_8 = new QWidget();
        tab_8->setObjectName(QString::fromUtf8("tab_8"));
        QFont font1;
        font1.setFamily(QString::fromUtf8("AR PL UKai CN"));
        font1.setPointSize(22);
        font1.setBold(false);
        font1.setItalic(false);
        font1.setWeight(50);
        tab_8->setFont(font1);
        widget_eng = new myDashboard(tab_8);
        widget_eng->setObjectName(QString::fromUtf8("widget_eng"));
        widget_eng->setGeometry(QRect(310, 170, 100, 100));
        eng_chg = new MQlabel(tab_8);
        eng_chg->setObjectName(QString::fromUtf8("eng_chg"));
        eng_chg->setGeometry(QRect(640, 6, 58, 45));
        eng_chg->setStyleSheet(QString::fromUtf8("background-image: url(:/images/engine/charging.png);"));
        l_preheat = new MQlabel(tab_8);
        l_preheat->setObjectName(QString::fromUtf8("l_preheat"));
        l_preheat->setGeometry(QRect(590, 10, 30, 30));
        l_preheat->setStyleSheet(QString::fromUtf8("border-image: url(:/images/engine/preheat.png);"));
        eng_gear = new QLabel(tab_8);
        eng_gear->setObjectName(QString::fromUtf8("eng_gear"));
        eng_gear->setGeometry(QRect(310, 5, 40, 40));
        eng_gear->setStyleSheet(QString::fromUtf8("border-image: url(:/images/engine/N.png);\n"
"background-color: transparent;"));
        eng_hb = new MQlabel(tab_8);
        eng_hb->setObjectName(QString::fromUtf8("eng_hb"));
        eng_hb->setGeometry(QRect(500, 9, 30, 30));
        eng_hb->setStyleSheet(QString::fromUtf8("border-image: url(:/images/engine/handbrake.png);"));
        l_turn_lf = new MQlabel(tab_8);
        l_turn_lf->setObjectName(QString::fromUtf8("l_turn_lf"));
        l_turn_lf->setGeometry(QRect(240, 10, 30, 30));
        l_turn_lf->setStyleSheet(QString::fromUtf8("border-image: url(:/images/engine/turn_left.png);"));
        l_turn_rt = new MQlabel(tab_8);
        l_turn_rt->setObjectName(QString::fromUtf8("l_turn_rt"));
        l_turn_rt->setGeometry(QRect(410, 10, 30, 30));
        l_turn_rt->setStyleSheet(QString::fromUtf8("border-image: url(:/images/engine/turn_right.png);"));
        widget_Tach = new Engtach(tab_8);
        widget_Tach->setObjectName(QString::fromUtf8("widget_Tach"));
        widget_Tach->setGeometry(QRect(310, 60, 100, 100));
        l_highlight = new MQlabel(tab_8);
        l_highlight->setObjectName(QString::fromUtf8("l_highlight"));
        l_highlight->setGeometry(QRect(280, 11, 30, 30));
        l_highlight->setStyleSheet(QString::fromUtf8("border-image: url(:/images/engine/highbeam.png);"));
        l_eng_fault = new MQlabel(tab_8);
        l_eng_fault->setObjectName(QString::fromUtf8("l_eng_fault"));
        l_eng_fault->setGeometry(QRect(100, 8, 35, 35));
        l_eng_fault->setStyleSheet(QString::fromUtf8("border-image: url(:/images/engine/engine_fault.png);"));
        l_full = new MQlabel(tab_8);
        l_full->setObjectName(QString::fromUtf8("l_full"));
        l_full->setGeometry(QRect(10, 7, 35, 35));
        l_full->setStyleSheet(QString::fromUtf8("border-image: url(:/images/engine/full2.png);"));
        l_clutch_st = new QLabel(tab_8);
        l_clutch_st->setObjectName(QString::fromUtf8("l_clutch_st"));
        l_clutch_st->setGeometry(QRect(550, 9, 30, 30));
        l_clutch_st->setStyleSheet(QString::fromUtf8("border-image: url(:/images/engine/clutch_on.png);"));
        l_indt_lm = new QLabel(tab_8);
        l_indt_lm->setObjectName(QString::fromUtf8("l_indt_lm"));
        l_indt_lm->setGeometry(QRect(190, 8, 35, 35));
        l_indt_lm->setStyleSheet(QString::fromUtf8("border-image: url(:/images/engine/Indt_lamp.png);"));
        l_air_cln = new MQlabel(tab_8);
        l_air_cln->setObjectName(QString::fromUtf8("l_air_cln"));
        l_air_cln->setGeometry(QRect(140, 11, 40, 30));
        l_air_cln->setStyleSheet(QString::fromUtf8("border-image: url(:/images/engine/air_cleaner.png);"));
        l_oil_water = new MQlabel(tab_8);
        l_oil_water->setObjectName(QString::fromUtf8("l_oil_water"));
        l_oil_water->setGeometry(QRect(60, 10, 30, 30));
        l_oil_water->setStyleSheet(QString::fromUtf8("border-image: url(:/images/engine/oil_water.png);"));
        scrollArea_11 = new QScrollArea(tab_8);
        scrollArea_11->setObjectName(QString::fromUtf8("scrollArea_11"));
        scrollArea_11->setGeometry(QRect(20, 50, 231, 341));
        scrollArea_11->setWidgetResizable(true);
        scrollAreaWidgetContents_11 = new QWidget();
        scrollAreaWidgetContents_11->setObjectName(QString::fromUtf8("scrollAreaWidgetContents_11"));
        scrollAreaWidgetContents_11->setGeometry(QRect(0, 0, 229, 339));
        w_elevator = new MQlabel(scrollAreaWidgetContents_11);
        w_elevator->setObjectName(QString::fromUtf8("w_elevator"));
        w_elevator->setGeometry(QRect(180, 300, 40, 40));
        w_elevator->setStyleSheet(QString::fromUtf8("border-image: url(:/images/engine/warning.png);"));
        label_62 = new QLabel(scrollAreaWidgetContents_11);
        label_62->setObjectName(QString::fromUtf8("label_62"));
        label_62->setGeometry(QRect(10, 100, 40, 40));
        label_62->setStyleSheet(QString::fromUtf8("border-image: url(:/images/engine/draught_fan.png);"));
        label_34 = new QLabel(scrollAreaWidgetContents_11);
        label_34->setObjectName(QString::fromUtf8("label_34"));
        label_34->setGeometry(QRect(11, 248, 35, 35));
        label_34->setStyleSheet(QString::fromUtf8("border-image: url(:/images/engine/ReThreshing.png);"));
        label_8 = new QLabel(scrollAreaWidgetContents_11);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(10, 9, 40, 40));
        label_8->setStyleSheet(QString::fromUtf8("border-image: url(:/images/engine/ReelSpeed.png);"));
        l_dtfan_sp = new QLabel(scrollAreaWidgetContents_11);
        l_dtfan_sp->setObjectName(QString::fromUtf8("l_dtfan_sp"));
        l_dtfan_sp->setGeometry(QRect(67, 102, 60, 31));
        l_dtfan_sp->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        w_rollerspeed = new MQlabel(scrollAreaWidgetContents_11);
        w_rollerspeed->setObjectName(QString::fromUtf8("w_rollerspeed"));
        w_rollerspeed->setGeometry(QRect(180, 200, 40, 40));
        w_rollerspeed->setStyleSheet(QString::fromUtf8("border-image: url(:/images/engine/warning.png);"));
        re_thr_sp = new QLabel(scrollAreaWidgetContents_11);
        re_thr_sp->setObjectName(QString::fromUtf8("re_thr_sp"));
        re_thr_sp->setGeometry(QRect(67, 251, 60, 31));
        re_thr_sp->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        w_re_thr_sp = new MQlabel(scrollAreaWidgetContents_11);
        w_re_thr_sp->setObjectName(QString::fromUtf8("w_re_thr_sp"));
        w_re_thr_sp->setGeometry(QRect(180, 250, 40, 40));
        w_re_thr_sp->setStyleSheet(QString::fromUtf8("border-image: url(:/images/engine/warning.png);"));
        w_cut_mach = new MQlabel(scrollAreaWidgetContents_11);
        w_cut_mach->setObjectName(QString::fromUtf8("w_cut_mach"));
        w_cut_mach->setGeometry(QRect(180, 57, 40, 40));
        w_cut_mach->setStyleSheet(QString::fromUtf8("border-image: url(:/images/engine/warning.png);"));
        label_63 = new QLabel(scrollAreaWidgetContents_11);
        label_63->setObjectName(QString::fromUtf8("label_63"));
        label_63->setGeometry(QRect(10, 58, 40, 40));
        label_63->setStyleSheet(QString::fromUtf8("border-image: url(:/images/engine/cut_mach.png);"));
        label_31 = new QLabel(scrollAreaWidgetContents_11);
        label_31->setObjectName(QString::fromUtf8("label_31"));
        label_31->setGeometry(QRect(9, 149, 40, 40));
        label_31->setStyleSheet(QString::fromUtf8("border-image: url(:/images/engine/FeedAugerSpeed.png);"));
        l_fdaugersp = new QLabel(scrollAreaWidgetContents_11);
        l_fdaugersp->setObjectName(QString::fromUtf8("l_fdaugersp"));
        l_fdaugersp->setGeometry(QRect(67, 151, 60, 31));
        l_fdaugersp->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_27 = new QLabel(scrollAreaWidgetContents_11);
        label_27->setObjectName(QString::fromUtf8("label_27"));
        label_27->setGeometry(QRect(10, 297, 40, 40));
        label_27->setStyleSheet(QString::fromUtf8("border-image: url(:/images/engine/Elevator.png);"));
        l_reedspeed = new QLabel(scrollAreaWidgetContents_11);
        l_reedspeed->setObjectName(QString::fromUtf8("l_reedspeed"));
        l_reedspeed->setGeometry(QRect(67, 10, 60, 31));
        l_reedspeed->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        w_fdaugersp = new MQlabel(scrollAreaWidgetContents_11);
        w_fdaugersp->setObjectName(QString::fromUtf8("w_fdaugersp"));
        w_fdaugersp->setGeometry(QRect(180, 150, 40, 40));
        w_fdaugersp->setStyleSheet(QString::fromUtf8("border-image: url(:/images/engine/warning.png);"));
        l_rollerspeed = new QLabel(scrollAreaWidgetContents_11);
        l_rollerspeed->setObjectName(QString::fromUtf8("l_rollerspeed"));
        l_rollerspeed->setGeometry(QRect(67, 200, 60, 31));
        l_rollerspeed->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        cut_mach = new QLabel(scrollAreaWidgetContents_11);
        cut_mach->setObjectName(QString::fromUtf8("cut_mach"));
        cut_mach->setGeometry(QRect(67, 58, 60, 31));
        cut_mach->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        w_dtfan_sp = new MQlabel(scrollAreaWidgetContents_11);
        w_dtfan_sp->setObjectName(QString::fromUtf8("w_dtfan_sp"));
        w_dtfan_sp->setGeometry(QRect(180, 100, 40, 40));
        w_dtfan_sp->setStyleSheet(QString::fromUtf8("border-image: url(:/images/engine/warning.png);"));
        l_elevator = new QLabel(scrollAreaWidgetContents_11);
        l_elevator->setObjectName(QString::fromUtf8("l_elevator"));
        l_elevator->setGeometry(QRect(67, 300, 60, 31));
        l_elevator->setStyleSheet(QString::fromUtf8(""));
        l_elevator->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_9 = new QLabel(scrollAreaWidgetContents_11);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(9, 197, 40, 40));
        label_9->setStyleSheet(QString::fromUtf8("border-image: url(:/images/engine/RollerSpeed.png);"));
        w_reed_speed = new MQlabel(scrollAreaWidgetContents_11);
        w_reed_speed->setObjectName(QString::fromUtf8("w_reed_speed"));
        w_reed_speed->setGeometry(QRect(180, 8, 40, 40));
        w_reed_speed->setStyleSheet(QString::fromUtf8("border-image: url(:/images/engine/warning.png);"));
        label = new QLabel(scrollAreaWidgetContents_11);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(130, 10, 45, 31));
        label_3 = new QLabel(scrollAreaWidgetContents_11);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(130, 58, 45, 31));
        label_4 = new QLabel(scrollAreaWidgetContents_11);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(130, 101, 45, 31));
        label_5 = new QLabel(scrollAreaWidgetContents_11);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(130, 201, 45, 31));
        label_10 = new QLabel(scrollAreaWidgetContents_11);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(130, 152, 45, 31));
        label_14 = new QLabel(scrollAreaWidgetContents_11);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(130, 251, 45, 31));
        label_15 = new QLabel(scrollAreaWidgetContents_11);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(130, 300, 45, 31));
        scrollArea_11->setWidget(scrollAreaWidgetContents_11);
        scrollArea_12 = new QScrollArea(tab_8);
        scrollArea_12->setObjectName(QString::fromUtf8("scrollArea_12"));
        scrollArea_12->setGeometry(QRect(470, 50, 191, 211));
        scrollArea_12->setWidgetResizable(true);
        scrollAreaWidgetContents_12 = new QWidget();
        scrollAreaWidgetContents_12->setObjectName(QString::fromUtf8("scrollAreaWidgetContents_12"));
        scrollAreaWidgetContents_12->setGeometry(QRect(0, 0, 189, 209));
        label_46 = new QLabel(scrollAreaWidgetContents_12);
        label_46->setObjectName(QString::fromUtf8("label_46"));
        label_46->setGeometry(QRect(10, 115, 40, 40));
        label_46->setStyleSheet(QString::fromUtf8("border-image: url(:/images/engine/CrushRate.png);"));
        dr_fan_impr_rate = new QLabel(scrollAreaWidgetContents_12);
        dr_fan_impr_rate->setObjectName(QString::fromUtf8("dr_fan_impr_rate"));
        dr_fan_impr_rate->setGeometry(QRect(60, 10, 60, 33));
        dr_fan_impr_rate->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        dr_fan_rate = new QLabel(scrollAreaWidgetContents_12);
        dr_fan_rate->setObjectName(QString::fromUtf8("dr_fan_rate"));
        dr_fan_rate->setGeometry(QRect(60, 40, 60, 33));
        dr_fan_rate->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        l_crushrate = new QLabel(scrollAreaWidgetContents_12);
        l_crushrate->setObjectName(QString::fromUtf8("l_crushrate"));
        l_crushrate->setGeometry(QRect(60, 120, 60, 31));
        l_crushrate->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_107 = new QLabel(scrollAreaWidgetContents_12);
        label_107->setObjectName(QString::fromUtf8("label_107"));
        label_107->setGeometry(QRect(10, 40, 40, 40));
        label_107->setStyleSheet(QString::fromUtf8("border-image: url(:/images/engine/draught_fan_rate.png);"));
        label_106 = new QLabel(scrollAreaWidgetContents_12);
        label_106->setObjectName(QString::fromUtf8("label_106"));
        label_106->setGeometry(QRect(10, 6, 40, 40));
        label_106->setStyleSheet(QString::fromUtf8("border-image: url(:/images/engine/draught_fanimpurity_rate.png);"));
        label_111 = new QLabel(scrollAreaWidgetContents_12);
        label_111->setObjectName(QString::fromUtf8("label_111"));
        label_111->setGeometry(QRect(10, 80, 40, 40));
        label_111->setStyleSheet(QString::fromUtf8("border-image: url(:/images/engine/DriftLoseRate.png);"));
        drift_lose_rate = new QLabel(scrollAreaWidgetContents_12);
        drift_lose_rate->setObjectName(QString::fromUtf8("drift_lose_rate"));
        drift_lose_rate->setGeometry(QRect(60, 80, 60, 33));
        drift_lose_rate->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        impr_rate = new QLabel(scrollAreaWidgetContents_12);
        impr_rate->setObjectName(QString::fromUtf8("impr_rate"));
        impr_rate->setGeometry(QRect(150, 13, 30, 30));
        impr_rate->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_23 = new QLabel(scrollAreaWidgetContents_12);
        label_23->setObjectName(QString::fromUtf8("label_23"));
        label_23->setGeometry(QRect(120, 12, 30, 31));
        label_29 = new QLabel(scrollAreaWidgetContents_12);
        label_29->setObjectName(QString::fromUtf8("label_29"));
        label_29->setGeometry(QRect(120, 42, 45, 31));
        label_32 = new QLabel(scrollAreaWidgetContents_12);
        label_32->setObjectName(QString::fromUtf8("label_32"));
        label_32->setGeometry(QRect(120, 82, 45, 31));
        label_41 = new QLabel(scrollAreaWidgetContents_12);
        label_41->setObjectName(QString::fromUtf8("label_41"));
        label_41->setGeometry(QRect(120, 120, 45, 31));
        label_102 = new QLabel(scrollAreaWidgetContents_12);
        label_102->setObjectName(QString::fromUtf8("label_102"));
        label_102->setGeometry(QRect(120, 162, 45, 31));
        label_88 = new QLabel(scrollAreaWidgetContents_12);
        label_88->setObjectName(QString::fromUtf8("label_88"));
        label_88->setGeometry(QRect(60, 160, 60, 33));
        label_88->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_65 = new QLabel(scrollAreaWidgetContents_12);
        label_65->setObjectName(QString::fromUtf8("label_65"));
        label_65->setGeometry(QRect(10, 160, 39, 40));
        label_65->setStyleSheet(QString::fromUtf8("border-image: url(:/images/parameters/CutLossRate.png);"));
        scrollArea_12->setWidget(scrollAreaWidgetContents_12);
        scrollArea_13 = new QScrollArea(tab_8);
        scrollArea_13->setObjectName(QString::fromUtf8("scrollArea_13"));
        scrollArea_13->setGeometry(QRect(470, 270, 191, 121));
        scrollArea_13->setWidgetResizable(true);
        scrollAreaWidgetContents_13 = new QWidget();
        scrollAreaWidgetContents_13->setObjectName(QString::fromUtf8("scrollAreaWidgetContents_13"));
        scrollAreaWidgetContents_13->setGeometry(QRect(0, 0, 189, 119));
        totle_km = new QLabel(scrollAreaWidgetContents_13);
        totle_km->setObjectName(QString::fromUtf8("totle_km"));
        totle_km->setGeometry(QRect(20, 0, 100, 30));
        totle_km->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        totle_tm = new QLabel(scrollAreaWidgetContents_13);
        totle_tm->setObjectName(QString::fromUtf8("totle_tm"));
        totle_tm->setGeometry(QRect(20, 40, 100, 30));
        totle_tm->setFont(font1);
        totle_tm->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        totle_m = new QLabel(scrollAreaWidgetContents_13);
        totle_m->setObjectName(QString::fromUtf8("totle_m"));
        totle_m->setGeometry(QRect(20, 81, 100, 30));
        totle_m->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_49 = new QLabel(scrollAreaWidgetContents_13);
        label_49->setObjectName(QString::fromUtf8("label_49"));
        label_49->setGeometry(QRect(120, 0, 45, 31));
        label_51 = new QLabel(scrollAreaWidgetContents_13);
        label_51->setObjectName(QString::fromUtf8("label_51"));
        label_51->setGeometry(QRect(120, 40, 45, 31));
        label_52 = new QLabel(scrollAreaWidgetContents_13);
        label_52->setObjectName(QString::fromUtf8("label_52"));
        label_52->setGeometry(QRect(120, 80, 45, 31));
        scrollArea_13->setWidget(scrollAreaWidgetContents_13);
        l_diplight = new MQlabel(tab_8);
        l_diplight->setObjectName(QString::fromUtf8("l_diplight"));
        l_diplight->setGeometry(QRect(360, 10, 30, 30));
        l_diplight->setStyleSheet(QString::fromUtf8("border-image: url(:/images/engine/diplight.png);"));
        scrollArea_10 = new QScrollArea(tab_8);
        scrollArea_10->setObjectName(QString::fromUtf8("scrollArea_10"));
        scrollArea_10->setGeometry(QRect(680, 50, 91, 341));
        scrollArea_10->setWidgetResizable(true);
        scrollAreaWidgetContents_10 = new QWidget();
        scrollAreaWidgetContents_10->setObjectName(QString::fromUtf8("scrollAreaWidgetContents_10"));
        scrollAreaWidgetContents_10->setGeometry(QRect(0, 0, 89, 339));
        label_21 = new QLabel(scrollAreaWidgetContents_10);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setGeometry(QRect(44, 300, 42, 31));
        w_eopres = new myProgressBar(scrollAreaWidgetContents_10);
        w_eopres->setObjectName(QString::fromUtf8("w_eopres"));
        w_eopres->setGeometry(QRect(20, 10, 50, 271));
        label_20 = new QLabel(scrollAreaWidgetContents_10);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setGeometry(QRect(1, 299, 40, 30));
        label_20->setStyleSheet(QString::fromUtf8("background-image: url(:/images/engine/eng_oil_prs.png);"));
        scrollArea_10->setWidget(scrollAreaWidgetContents_10);
        scrollArea_14 = new QScrollArea(tab_8);
        scrollArea_14->setObjectName(QString::fromUtf8("scrollArea_14"));
        scrollArea_14->setGeometry(QRect(270, 290, 181, 101));
        scrollArea_14->setWidgetResizable(true);
        scrollAreaWidgetContents_14 = new QWidget();
        scrollAreaWidgetContents_14->setObjectName(QString::fromUtf8("scrollAreaWidgetContents_14"));
        scrollAreaWidgetContents_14->setGeometry(QRect(0, 0, 179, 99));
        l_eng_them = new QLabel(scrollAreaWidgetContents_14);
        l_eng_them->setObjectName(QString::fromUtf8("l_eng_them"));
        l_eng_them->setGeometry(QRect(70, 53, 50, 30));
        l_eng_them->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        l_eng_sm = new QLabel(scrollAreaWidgetContents_14);
        l_eng_sm->setObjectName(QString::fromUtf8("l_eng_sm"));
        l_eng_sm->setGeometry(QRect(70, 10, 50, 30));
        l_eng_sm->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_16 = new QLabel(scrollAreaWidgetContents_14);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setGeometry(QRect(23, 49, 40, 40));
        label_16->setStyleSheet(QString::fromUtf8("border-image: url(:/images/engine/eng_tem.png);"));
        label_7 = new QLabel(scrollAreaWidgetContents_14);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(20, 11, 40, 38));
        label_7->setStyleSheet(QString::fromUtf8("border-image: url(:/images/engine/fuel.png);"));
        label_19 = new QLabel(scrollAreaWidgetContents_14);
        label_19->setObjectName(QString::fromUtf8("label_19"));
        label_19->setGeometry(QRect(120, 10, 45, 31));
        label_22 = new QLabel(scrollAreaWidgetContents_14);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setGeometry(QRect(120, 53, 45, 31));
        scrollArea_14->setWidget(scrollAreaWidgetContents_14);
        l_voltage = new QLabel(tab_8);
        l_voltage->setObjectName(QString::fromUtf8("l_voltage"));
        l_voltage->setGeometry(QRect(705, 0, 91, 41));
        l_voltage->setFont(font1);
        l_voltage->setStyleSheet(QString::fromUtf8("background-color: rgb(251, 241, 6);"));
        l_unloader = new QLabel(tab_8);
        l_unloader->setObjectName(QString::fromUtf8("l_unloader"));
        l_unloader->setGeometry(QRect(450, 10, 30, 30));
        l_unloader->setStyleSheet(QString::fromUtf8("border-image: url(:/images/parameters/UnloaderOn.png);"));
        QIcon icon1;
        icon1.addFile(QString::fromUtf8(":/images/harvester.png"), QSize(), QIcon::Normal, QIcon::Off);
        tabWidget->addTab(tab_8, icon1, QString());
        tab = new QWidget();
        tab->setObjectName(QString::fromUtf8("tab"));
        scrollArea = new QScrollArea(tab);
        scrollArea->setObjectName(QString::fromUtf8("scrollArea"));
        scrollArea->setGeometry(QRect(490, 10, 181, 251));
        scrollArea->setWidgetResizable(true);
        scrollAreaWidgetContents = new QWidget();
        scrollAreaWidgetContents->setObjectName(QString::fromUtf8("scrollAreaWidgetContents"));
        scrollAreaWidgetContents->setGeometry(QRect(0, 0, 179, 249));
        label_96 = new QLabel(scrollAreaWidgetContents);
        label_96->setObjectName(QString::fromUtf8("label_96"));
        label_96->setGeometry(QRect(70, 208, 60, 33));
        label_96->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_28 = new QLabel(scrollAreaWidgetContents);
        label_28->setObjectName(QString::fromUtf8("label_28"));
        label_28->setGeometry(QRect(10, 161, 40, 40));
        label_28->setStyleSheet(QString::fromUtf8("border-image: url(:/images/parameters/CutHeightLeft.png);"));
        label_59 = new QLabel(scrollAreaWidgetContents);
        label_59->setObjectName(QString::fromUtf8("label_59"));
        label_59->setGeometry(QRect(10, 48, 40, 40));
        label_59->setStyleSheet(QString::fromUtf8("border-image: url(:/images/parameters/ReelShift.png);"));
        profiling_height = new QLabel(scrollAreaWidgetContents);
        profiling_height->setObjectName(QString::fromUtf8("profiling_height"));
        profiling_height->setGeometry(QRect(70, -2, 60, 33));
        profiling_height->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_95 = new QLabel(scrollAreaWidgetContents);
        label_95->setObjectName(QString::fromUtf8("label_95"));
        label_95->setGeometry(QRect(70, 163, 60, 33));
        label_95->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        reel_height = new QLabel(scrollAreaWidgetContents);
        reel_height->setObjectName(QString::fromUtf8("reel_height"));
        reel_height->setGeometry(QRect(70, 107, 60, 33));
        reel_height->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_68 = new QLabel(scrollAreaWidgetContents);
        label_68->setObjectName(QString::fromUtf8("label_68"));
        label_68->setGeometry(QRect(10, 208, 40, 40));
        label_68->setStyleSheet(QString::fromUtf8("border-image: url(:/images/parameters/CutHeightRight.png);"));
        reel_shift = new QLabel(scrollAreaWidgetContents);
        reel_shift->setObjectName(QString::fromUtf8("reel_shift"));
        reel_shift->setGeometry(QRect(70, 48, 60, 33));
        reel_shift->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_25 = new QLabel(scrollAreaWidgetContents);
        label_25->setObjectName(QString::fromUtf8("label_25"));
        label_25->setGeometry(QRect(10, -2, 40, 40));
        label_25->setStyleSheet(QString::fromUtf8("border-image: url(:/images/parameters/ProfilingHeight.png);"));
        label_43 = new QLabel(scrollAreaWidgetContents);
        label_43->setObjectName(QString::fromUtf8("label_43"));
        label_43->setGeometry(QRect(13, 105, 40, 40));
        label_43->setStyleSheet(QString::fromUtf8("border-image: url(:/images/parameters/ReelHeight.png);"));
        label_92 = new QLabel(scrollAreaWidgetContents);
        label_92->setObjectName(QString::fromUtf8("label_92"));
        label_92->setGeometry(QRect(130, 0, 45, 31));
        label_93 = new QLabel(scrollAreaWidgetContents);
        label_93->setObjectName(QString::fromUtf8("label_93"));
        label_93->setGeometry(QRect(130, 50, 45, 31));
        label_94 = new QLabel(scrollAreaWidgetContents);
        label_94->setObjectName(QString::fromUtf8("label_94"));
        label_94->setGeometry(QRect(130, 110, 45, 31));
        label_97 = new QLabel(scrollAreaWidgetContents);
        label_97->setObjectName(QString::fromUtf8("label_97"));
        label_97->setGeometry(QRect(130, 166, 45, 31));
        label_98 = new QLabel(scrollAreaWidgetContents);
        label_98->setObjectName(QString::fromUtf8("label_98"));
        label_98->setGeometry(QRect(130, 208, 45, 31));
        scrollArea->setWidget(scrollAreaWidgetContents);
        scrollArea_2 = new QScrollArea(tab);
        scrollArea_2->setObjectName(QString::fromUtf8("scrollArea_2"));
        scrollArea_2->setGeometry(QRect(220, 10, 251, 251));
        scrollArea_2->setWidgetResizable(true);
        scrollAreaWidgetContents_2 = new QWidget();
        scrollAreaWidgetContents_2->setObjectName(QString::fromUtf8("scrollAreaWidgetContents_2"));
        scrollAreaWidgetContents_2->setGeometry(QRect(0, 0, 249, 249));
        roller_torque = new QLabel(scrollAreaWidgetContents_2);
        roller_torque->setObjectName(QString::fromUtf8("roller_torque"));
        roller_torque->setGeometry(QRect(70, 0, 100, 31));
        roller_torque->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        l_fan_angle = new QLabel(scrollAreaWidgetContents_2);
        l_fan_angle->setObjectName(QString::fromUtf8("l_fan_angle"));
        l_fan_angle->setGeometry(QRect(70, 90, 100, 33));
        l_fan_angle->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_54 = new QLabel(scrollAreaWidgetContents_2);
        label_54->setObjectName(QString::fromUtf8("label_54"));
        label_54->setGeometry(QRect(70, 41, 100, 33));
        label_54->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        front_motor_sp = new QLabel(scrollAreaWidgetContents_2);
        front_motor_sp->setObjectName(QString::fromUtf8("front_motor_sp"));
        front_motor_sp->setGeometry(QRect(90, 141, 60, 33));
        front_motor_sp->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        rear_motor_sp = new QLabel(scrollAreaWidgetContents_2);
        rear_motor_sp->setObjectName(QString::fromUtf8("rear_motor_sp"));
        rear_motor_sp->setGeometry(QRect(90, 185, 60, 33));
        rear_motor_sp->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        layoutWidget = new QWidget(scrollAreaWidgetContents_2);
        layoutWidget->setObjectName(QString::fromUtf8("layoutWidget"));
        layoutWidget->setGeometry(QRect(7, 0, 41, 221));
        verticalLayout_3 = new QVBoxLayout(layoutWidget);
        verticalLayout_3->setSpacing(6);
        verticalLayout_3->setContentsMargins(11, 11, 11, 11);
        verticalLayout_3->setObjectName(QString::fromUtf8("verticalLayout_3"));
        verticalLayout_3->setContentsMargins(0, 0, 0, 0);
        label_64 = new QLabel(layoutWidget);
        label_64->setObjectName(QString::fromUtf8("label_64"));
        label_64->setStyleSheet(QString::fromUtf8("border-image: url(:/images/parameters/RollerTorque.png);"));

        verticalLayout_3->addWidget(label_64);

        label_66 = new QLabel(layoutWidget);
        label_66->setObjectName(QString::fromUtf8("label_66"));
        label_66->setStyleSheet(QString::fromUtf8("border-image: url(:/images/parameters/ThrowMachineAngle.png);"));

        verticalLayout_3->addWidget(label_66);

        label_67 = new QLabel(layoutWidget);
        label_67->setObjectName(QString::fromUtf8("label_67"));
        label_67->setStyleSheet(QString::fromUtf8("border-image: url(:/images/parameters/FanAngle.png);"));

        verticalLayout_3->addWidget(label_67);

        label_44 = new QLabel(layoutWidget);
        label_44->setObjectName(QString::fromUtf8("label_44"));
        label_44->setStyleSheet(QString::fromUtf8("border-image: url(:/images/parameters/FrontMotorSpeed.png);"));

        verticalLayout_3->addWidget(label_44);

        label_50 = new QLabel(layoutWidget);
        label_50->setObjectName(QString::fromUtf8("label_50"));
        label_50->setStyleSheet(QString::fromUtf8("border-image: url(:/images/parameters/RearMotorSpeed.png);"));

        verticalLayout_3->addWidget(label_50);

        w_front_motor_sp = new MQlabel(scrollAreaWidgetContents_2);
        w_front_motor_sp->setObjectName(QString::fromUtf8("w_front_motor_sp"));
        w_front_motor_sp->setGeometry(QRect(200, 140, 40, 40));
        w_front_motor_sp->setStyleSheet(QString::fromUtf8("border-image: url(:/images/engine/warning.png);"));
        w_rear_motor_sp = new MQlabel(scrollAreaWidgetContents_2);
        w_rear_motor_sp->setObjectName(QString::fromUtf8("w_rear_motor_sp"));
        w_rear_motor_sp->setGeometry(QRect(200, 182, 40, 40));
        w_rear_motor_sp->setStyleSheet(QString::fromUtf8("border-image: url(:/images/engine/warning.png);"));
        label_83 = new QLabel(scrollAreaWidgetContents_2);
        label_83->setObjectName(QString::fromUtf8("label_83"));
        label_83->setGeometry(QRect(170, 0, 45, 31));
        label_84 = new QLabel(scrollAreaWidgetContents_2);
        label_84->setObjectName(QString::fromUtf8("label_84"));
        label_84->setGeometry(QRect(170, 43, 45, 31));
        label_86 = new QLabel(scrollAreaWidgetContents_2);
        label_86->setObjectName(QString::fromUtf8("label_86"));
        label_86->setGeometry(QRect(170, 92, 45, 31));
        label_87 = new QLabel(scrollAreaWidgetContents_2);
        label_87->setObjectName(QString::fromUtf8("label_87"));
        label_87->setGeometry(QRect(150, 142, 45, 31));
        label_89 = new QLabel(scrollAreaWidgetContents_2);
        label_89->setObjectName(QString::fromUtf8("label_89"));
        label_89->setGeometry(QRect(150, 186, 45, 31));
        scrollArea_2->setWidget(scrollAreaWidgetContents_2);
        scrollArea_3 = new QScrollArea(tab);
        scrollArea_3->setObjectName(QString::fromUtf8("scrollArea_3"));
        scrollArea_3->setGeometry(QRect(20, 10, 181, 251));
        scrollArea_3->setWidgetResizable(true);
        scrollAreaWidgetContents_3 = new QWidget();
        scrollAreaWidgetContents_3->setObjectName(QString::fromUtf8("scrollAreaWidgetContents_3"));
        scrollAreaWidgetContents_3->setGeometry(QRect(0, 0, 179, 249));
        label_61 = new QLabel(scrollAreaWidgetContents_3);
        label_61->setObjectName(QString::fromUtf8("label_61"));
        label_61->setGeometry(QRect(60, 200, 60, 41));
        label_61->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_56 = new QLabel(scrollAreaWidgetContents_3);
        label_56->setObjectName(QString::fromUtf8("label_56"));
        label_56->setGeometry(QRect(1, 165, 40, 40));
        label_56->setStyleSheet(QString::fromUtf8("border-image: url(:/images/parameters/sorting_screen_down.png);"));
        label_18 = new QLabel(scrollAreaWidgetContents_3);
        label_18->setObjectName(QString::fromUtf8("label_18"));
        label_18->setGeometry(QRect(1, 82, 40, 40));
        label_18->setStyleSheet(QString::fromUtf8("border-image: url(:/images/parameters/ConcaveClearance.png);"));
        label_60 = new QLabel(scrollAreaWidgetContents_3);
        label_60->setObjectName(QString::fromUtf8("label_60"));
        label_60->setGeometry(QRect(60, 160, 60, 41));
        label_60->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_40 = new QLabel(scrollAreaWidgetContents_3);
        label_40->setObjectName(QString::fromUtf8("label_40"));
        label_40->setGeometry(QRect(60, 46, 60, 30));
        label_40->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_17 = new QLabel(scrollAreaWidgetContents_3);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setGeometry(QRect(1, 125, 40, 40));
        label_17->setStyleSheet(QString::fromUtf8("border-image: url(:/images/parameters/sorting_screen_up.png);"));
        label_58 = new QLabel(scrollAreaWidgetContents_3);
        label_58->setObjectName(QString::fromUtf8("label_58"));
        label_58->setGeometry(QRect(60, 120, 60, 41));
        label_58->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_24 = new QLabel(scrollAreaWidgetContents_3);
        label_24->setObjectName(QString::fromUtf8("label_24"));
        label_24->setGeometry(QRect(1, 0, 40, 40));
        label_24->setStyleSheet(QString::fromUtf8("border-image: url(:/images/con_recong/cut_height.png);"));
        label_38 = new QLabel(scrollAreaWidgetContents_3);
        label_38->setObjectName(QString::fromUtf8("label_38"));
        label_38->setGeometry(QRect(5, 48, 30, 30));
        label_38->setStyleSheet(QString::fromUtf8("border-image: url(:/images/parameters/GrainHeight.png);"));
        l_concavecl = new QLabel(scrollAreaWidgetContents_3);
        l_concavecl->setObjectName(QString::fromUtf8("l_concavecl"));
        l_concavecl->setGeometry(QRect(60, 84, 60, 33));
        l_concavecl->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_57 = new QLabel(scrollAreaWidgetContents_3);
        label_57->setObjectName(QString::fromUtf8("label_57"));
        label_57->setGeometry(QRect(1, 205, 40, 40));
        label_57->setStyleSheet(QString::fromUtf8("border-image: url(:/images/parameters/sorting_screen_tail.png);"));
        label_30 = new QLabel(scrollAreaWidgetContents_3);
        label_30->setObjectName(QString::fromUtf8("label_30"));
        label_30->setGeometry(QRect(60, 10, 60, 21));
        label_30->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_73 = new QLabel(scrollAreaWidgetContents_3);
        label_73->setObjectName(QString::fromUtf8("label_73"));
        label_73->setGeometry(QRect(120, 5, 45, 31));
        label_74 = new QLabel(scrollAreaWidgetContents_3);
        label_74->setObjectName(QString::fromUtf8("label_74"));
        label_74->setGeometry(QRect(120, 46, 45, 31));
        label_77 = new QLabel(scrollAreaWidgetContents_3);
        label_77->setObjectName(QString::fromUtf8("label_77"));
        label_77->setGeometry(QRect(120, 86, 45, 31));
        label_78 = new QLabel(scrollAreaWidgetContents_3);
        label_78->setObjectName(QString::fromUtf8("label_78"));
        label_78->setGeometry(QRect(120, 125, 45, 31));
        label_79 = new QLabel(scrollAreaWidgetContents_3);
        label_79->setObjectName(QString::fromUtf8("label_79"));
        label_79->setGeometry(QRect(120, 165, 45, 31));
        label_80 = new QLabel(scrollAreaWidgetContents_3);
        label_80->setObjectName(QString::fromUtf8("label_80"));
        label_80->setGeometry(QRect(120, 205, 45, 31));
        scrollArea_3->setWidget(scrollAreaWidgetContents_3);
        scrollArea_4 = new QScrollArea(tab);
        scrollArea_4->setObjectName(QString::fromUtf8("scrollArea_4"));
        scrollArea_4->setGeometry(QRect(20, 264, 181, 131));
        scrollArea_4->setWidgetResizable(true);
        scrollAreaWidgetContents_4 = new QWidget();
        scrollAreaWidgetContents_4->setObjectName(QString::fromUtf8("scrollAreaWidgetContents_4"));
        scrollAreaWidgetContents_4->setGeometry(QRect(0, 0, 179, 129));
        weight_wet = new QLabel(scrollAreaWidgetContents_4);
        weight_wet->setObjectName(QString::fromUtf8("weight_wet"));
        weight_wet->setGeometry(QRect(60, 70, 60, 33));
        weight_wet->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_36 = new QLabel(scrollAreaWidgetContents_4);
        label_36->setObjectName(QString::fromUtf8("label_36"));
        label_36->setGeometry(QRect(0, 19, 40, 40));
        label_36->setStyleSheet(QString::fromUtf8("border-image: url(:/images/parameters/WeightDry.png);"));
        weight_dry = new QLabel(scrollAreaWidgetContents_4);
        weight_dry->setObjectName(QString::fromUtf8("weight_dry"));
        weight_dry->setGeometry(QRect(60, 28, 60, 33));
        weight_dry->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_37 = new QLabel(scrollAreaWidgetContents_4);
        label_37->setObjectName(QString::fromUtf8("label_37"));
        label_37->setGeometry(QRect(0, 61, 40, 40));
        label_37->setStyleSheet(QString::fromUtf8("border-image: url(:/images/parameters/WeightWet.png);"));
        label_81 = new QLabel(scrollAreaWidgetContents_4);
        label_81->setObjectName(QString::fromUtf8("label_81"));
        label_81->setGeometry(QRect(120, 30, 45, 31));
        label_82 = new QLabel(scrollAreaWidgetContents_4);
        label_82->setObjectName(QString::fromUtf8("label_82"));
        label_82->setGeometry(QRect(120, 70, 45, 31));
        scrollArea_4->setWidget(scrollAreaWidgetContents_4);
        scrollArea_5 = new QScrollArea(tab);
        scrollArea_5->setObjectName(QString::fromUtf8("scrollArea_5"));
        scrollArea_5->setGeometry(QRect(490, 265, 181, 131));
        scrollArea_5->setWidgetResizable(true);
        scrollAreaWidgetContents_5 = new QWidget();
        scrollAreaWidgetContents_5->setObjectName(QString::fromUtf8("scrollAreaWidgetContents_5"));
        scrollAreaWidgetContents_5->setGeometry(QRect(0, 0, 179, 129));
        water_rate = new QLabel(scrollAreaWidgetContents_5);
        water_rate->setObjectName(QString::fromUtf8("water_rate"));
        water_rate->setGeometry(QRect(60, 51, 80, 33));
        water_rate->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_55 = new QLabel(scrollAreaWidgetContents_5);
        label_55->setObjectName(QString::fromUtf8("label_55"));
        label_55->setGeometry(QRect(10, 2, 40, 40));
        label_55->setStyleSheet(QString::fromUtf8("border-image: url(:/images/parameters/GrainQualityMonitor.png);"));
        grain_quality_monitor = new QLabel(scrollAreaWidgetContents_5);
        grain_quality_monitor->setObjectName(QString::fromUtf8("grain_quality_monitor"));
        grain_quality_monitor->setGeometry(QRect(60, 10, 80, 33));
        grain_quality_monitor->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_26 = new QLabel(scrollAreaWidgetContents_5);
        label_26->setObjectName(QString::fromUtf8("label_26"));
        label_26->setGeometry(QRect(11, 47, 40, 40));
        label_26->setStyleSheet(QString::fromUtf8("border-image: url(:/images/parameters/WaterRate.png);"));
        label_100 = new QLabel(scrollAreaWidgetContents_5);
        label_100->setObjectName(QString::fromUtf8("label_100"));
        label_100->setGeometry(QRect(140, 10, 45, 31));
        label_101 = new QLabel(scrollAreaWidgetContents_5);
        label_101->setObjectName(QString::fromUtf8("label_101"));
        label_101->setGeometry(QRect(140, 53, 45, 31));
        scrollArea_5->setWidget(scrollAreaWidgetContents_5);
        scrollArea_6 = new QScrollArea(tab);
        scrollArea_6->setObjectName(QString::fromUtf8("scrollArea_6"));
        scrollArea_6->setGeometry(QRect(220, 265, 251, 131));
        scrollArea_6->setWidgetResizable(true);
        scrollAreaWidgetContents_6 = new QWidget();
        scrollAreaWidgetContents_6->setObjectName(QString::fromUtf8("scrollAreaWidgetContents_6"));
        scrollAreaWidgetContents_6->setGeometry(QRect(0, 0, 249, 129));
        label_99 = new QLabel(scrollAreaWidgetContents_6);
        label_99->setObjectName(QString::fromUtf8("label_99"));
        label_99->setGeometry(QRect(70, 60, 80, 33));
        label_99->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_85 = new QLabel(scrollAreaWidgetContents_6);
        label_85->setObjectName(QString::fromUtf8("label_85"));
        label_85->setGeometry(QRect(70, 10, 80, 33));
        label_85->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_42 = new QLabel(scrollAreaWidgetContents_6);
        label_42->setObjectName(QString::fromUtf8("label_42"));
        label_42->setGeometry(QRect(10, 10, 40, 40));
        label_42->setStyleSheet(QString::fromUtf8("border-image: url(:/images/parameters/YieldPerSquare.png);"));
        label_69 = new QLabel(scrollAreaWidgetContents_6);
        label_69->setObjectName(QString::fromUtf8("label_69"));
        label_69->setGeometry(QRect(10, 60, 40, 40));
        label_69->setStyleSheet(QString::fromUtf8("border-image: url(:/images/parameters/FeedQuality.png);"));
        label_90 = new QLabel(scrollAreaWidgetContents_6);
        label_90->setObjectName(QString::fromUtf8("label_90"));
        label_90->setGeometry(QRect(150, 10, 80, 31));
        label_91 = new QLabel(scrollAreaWidgetContents_6);
        label_91->setObjectName(QString::fromUtf8("label_91"));
        label_91->setGeometry(QRect(150, 60, 80, 31));
        scrollArea_6->setWidget(scrollAreaWidgetContents_6);
        control_set = new QPushButton(tab);
        control_set->setObjectName(QString::fromUtf8("control_set"));
        control_set->setGeometry(QRect(690, 10, 89, 81));
        control_set->setStyleSheet(QString::fromUtf8("background-color: rgb(121, 242, 156);"));
        parameter_set = new QPushButton(tab);
        parameter_set->setObjectName(QString::fromUtf8("parameter_set"));
        parameter_set->setGeometry(QRect(690, 160, 89, 81));
        parameter_set->setStyleSheet(QString::fromUtf8("background-color: rgb(121, 242, 156);"));
        parameter_set_2 = new QPushButton(tab);
        parameter_set_2->setObjectName(QString::fromUtf8("parameter_set_2"));
        parameter_set_2->setGeometry(QRect(690, 315, 89, 81));
        label_47 = new QLabel(tab);
        label_47->setObjectName(QString::fromUtf8("label_47"));
        label_47->setGeometry(QRect(570, 354, 60, 33));
        label_47->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_48 = new QLabel(tab);
        label_48->setObjectName(QString::fromUtf8("label_48"));
        label_48->setGeometry(QRect(630, 356, 25, 31));
        label_112 = new QLabel(tab);
        label_112->setObjectName(QString::fromUtf8("label_112"));
        label_112->setGeometry(QRect(503, 354, 40, 40));
        label_112->setStyleSheet(QString::fromUtf8("border-image: url(:/images/engine/CutterHz.png);"));
        QIcon icon2;
        icon2.addFile(QString::fromUtf8(":/images/para.png"), QSize(), QIcon::Normal, QIcon::Off);
        tabWidget->addTab(tab, icon2, QString());
        tab_2 = new QWidget();
        tab_2->setObjectName(QString::fromUtf8("tab_2"));
        scrollArea_7 = new QScrollArea(tab_2);
        scrollArea_7->setObjectName(QString::fromUtf8("scrollArea_7"));
        scrollArea_7->setGeometry(QRect(120, 10, 221, 381));
        scrollArea_7->setWidgetResizable(true);
        scrollAreaWidgetContents_8 = new QWidget();
        scrollAreaWidgetContents_8->setObjectName(QString::fromUtf8("scrollAreaWidgetContents_8"));
        scrollAreaWidgetContents_8->setGeometry(QRect(0, 0, 219, 379));
        l_cuthei_down = new QLabel(scrollAreaWidgetContents_8);
        l_cuthei_down->setObjectName(QString::fromUtf8("l_cuthei_down"));
        l_cuthei_down->setGeometry(QRect(61, 80, 40, 40));
        l_cuthei_down->setStyleSheet(QString::fromUtf8("border-image: url(:/images/con_recong/CutHeiDownOff.png);"));
        l_reelval_down = new QLabel(scrollAreaWidgetContents_8);
        l_reelval_down->setObjectName(QString::fromUtf8("l_reelval_down"));
        l_reelval_down->setGeometry(QRect(172, 200, 40, 41));
        l_reelval_down->setStyleSheet(QString::fromUtf8("border-image: url(:/images/con_recong/ReelValveDownOff.png);"));
        l_reel_down = new QLabel(scrollAreaWidgetContents_8);
        l_reel_down->setObjectName(QString::fromUtf8("l_reel_down"));
        l_reel_down->setGeometry(QRect(61, 200, 40, 41));
        l_reel_down->setStyleSheet(QString::fromUtf8("border-image: url(:/images/con_recong/ReelDownOff.png);"));
        l_clusterval_off = new QLabel(scrollAreaWidgetContents_8);
        l_clusterval_off->setObjectName(QString::fromUtf8("l_clusterval_off"));
        l_clusterval_off->setGeometry(QRect(172, 20, 40, 40));
        l_clusterval_off->setStyleSheet(QString::fromUtf8("border-image: url(:/images/parameters/ClutchValveOffOn.png);"));
        s_minus = new QLabel(scrollAreaWidgetContents_8);
        s_minus->setObjectName(QString::fromUtf8("s_minus"));
        s_minus->setGeometry(QRect(61, 320, 40, 40));
        s_minus->setStyleSheet(QString::fromUtf8("border-image: url(:/images/con_recong/FanDownOn.png);"));
        l_cluster_off = new QLabel(scrollAreaWidgetContents_8);
        l_cluster_off->setObjectName(QString::fromUtf8("l_cluster_off"));
        l_cluster_off->setGeometry(QRect(61, 20, 40, 40));
        l_cluster_off->setStyleSheet(QString::fromUtf8("border-image: url(:/images/parameters/ClutchOffOff.png);"));
        s_plus = new QLabel(scrollAreaWidgetContents_8);
        s_plus->setObjectName(QString::fromUtf8("s_plus"));
        s_plus->setGeometry(QRect(8, 320, 39, 40));
        s_plus->setStyleSheet(QString::fromUtf8("border-image: url(:/images/con_recong/FanUpOff.png);"));
        l_clusterval_on = new QLabel(scrollAreaWidgetContents_8);
        l_clusterval_on->setObjectName(QString::fromUtf8("l_clusterval_on"));
        l_clusterval_on->setGeometry(QRect(115, 20, 39, 40));
        l_clusterval_on->setStyleSheet(QString::fromUtf8("border-image: url(:/images/parameters/ClutchValveOnOff.png);"));
        l_unswout = new QLabel(scrollAreaWidgetContents_8);
        l_unswout->setObjectName(QString::fromUtf8("l_unswout"));
        l_unswout->setGeometry(QRect(8, 260, 40, 40));
        l_unswout->setFont(font1);
        l_unswout->setStyleSheet(QString::fromUtf8("border-image: url(:/images/parameters/UnloaderSwingOutOff.png);"));
        l_unswin = new QLabel(scrollAreaWidgetContents_8);
        l_unswin->setObjectName(QString::fromUtf8("l_unswin"));
        l_unswin->setGeometry(QRect(61, 260, 40, 40));
        l_unswin->setStyleSheet(QString::fromUtf8("border-image: url(:/images/parameters/UnloaderSwingInOn.png);"));
        l_reelval_up = new QLabel(scrollAreaWidgetContents_8);
        l_reelval_up->setObjectName(QString::fromUtf8("l_reelval_up"));
        l_reelval_up->setGeometry(QRect(115, 200, 39, 41));
        l_reelval_up->setStyleSheet(QString::fromUtf8("border-image: url(:/images/con_recong/ReelValveUpOn.png);"));
        s_fan = new QLabel(scrollAreaWidgetContents_8);
        s_fan->setObjectName(QString::fromUtf8("s_fan"));
        s_fan->setGeometry(QRect(114, 320, 40, 40));
        QFont font2;
        font2.setFamily(QString::fromUtf8("AR PL UKai CN"));
        font2.setPointSize(22);
        font2.setBold(false);
        font2.setItalic(false);
        font2.setWeight(50);
        font2.setKerning(true);
        s_fan->setFont(font2);
        s_fan->setStyleSheet(QString::fromUtf8("border-image: url(:/images/parameters/s_on.png);"));
        l_reel_up = new QLabel(scrollAreaWidgetContents_8);
        l_reel_up->setObjectName(QString::fromUtf8("l_reel_up"));
        l_reel_up->setGeometry(QRect(8, 200, 40, 41));
        l_reel_up->setStyleSheet(QString::fromUtf8("border-image: url(:/images/con_recong/ReelUpOn.png);"));
        l_unswinval = new QLabel(scrollAreaWidgetContents_8);
        l_unswinval->setObjectName(QString::fromUtf8("l_unswinval"));
        l_unswinval->setGeometry(QRect(172, 260, 40, 40));
        l_unswinval->setStyleSheet(QString::fromUtf8("border-image: url(:/images/parameters/UnloaderValveSwingInOff.png);"));
        l_cuthei_up = new QLabel(scrollAreaWidgetContents_8);
        l_cuthei_up->setObjectName(QString::fromUtf8("l_cuthei_up"));
        l_cuthei_up->setGeometry(QRect(8, 80, 40, 40));
        l_cuthei_up->setStyleSheet(QString::fromUtf8("border-image: url(:/images/con_recong/CutHeiUpOn.png);"));
        l_unswoutval = new QLabel(scrollAreaWidgetContents_8);
        l_unswoutval->setObjectName(QString::fromUtf8("l_unswoutval"));
        l_unswoutval->setGeometry(QRect(115, 260, 39, 40));
        l_unswoutval->setStyleSheet(QString::fromUtf8("border-image: url(:/images/parameters/UnloaderValveSwingOutOn.png);"));
        l_rolval_down = new QLabel(scrollAreaWidgetContents_8);
        l_rolval_down->setObjectName(QString::fromUtf8("l_rolval_down"));
        l_rolval_down->setGeometry(QRect(172, 140, 40, 40));
        l_rolval_down->setStyleSheet(QString::fromUtf8("border-image: url(:/images/con_recong/RollerValveDownOn.png);"));
        l_cutheival_down = new QLabel(scrollAreaWidgetContents_8);
        l_cutheival_down->setObjectName(QString::fromUtf8("l_cutheival_down"));
        l_cutheival_down->setGeometry(QRect(172, 80, 40, 40));
        l_cutheival_down->setStyleSheet(QString::fromUtf8("border-image: url(:/images/con_recong/CutHeiValveDownOn.png);"));
        l_cutheival_up = new QLabel(scrollAreaWidgetContents_8);
        l_cutheival_up->setObjectName(QString::fromUtf8("l_cutheival_up"));
        l_cutheival_up->setGeometry(QRect(115, 80, 39, 40));
        l_cutheival_up->setStyleSheet(QString::fromUtf8("border-image: url(:/images/con_recong/CutHeiValveUpOff.png);"));
        l_rolval_up = new QLabel(scrollAreaWidgetContents_8);
        l_rolval_up->setObjectName(QString::fromUtf8("l_rolval_up"));
        l_rolval_up->setGeometry(QRect(115, 140, 39, 40));
        l_rolval_up->setStyleSheet(QString::fromUtf8("border-image: url(:/images/con_recong/RollerValveUpOff.png);"));
        l_cluster_on = new QLabel(scrollAreaWidgetContents_8);
        l_cluster_on->setObjectName(QString::fromUtf8("l_cluster_on"));
        l_cluster_on->setGeometry(QRect(8, 20, 40, 40));
        l_cluster_on->setStyleSheet(QString::fromUtf8("border-image: url(:/images/parameters/ClutchOnOn.png);"));
        l_rol_down = new QLabel(scrollAreaWidgetContents_8);
        l_rol_down->setObjectName(QString::fromUtf8("l_rol_down"));
        l_rol_down->setGeometry(QRect(61, 140, 40, 40));
        l_rol_down->setStyleSheet(QString::fromUtf8("border-image: url(:/images/con_recong/RollerDownOff.png);"));
        l_rol_up = new QLabel(scrollAreaWidgetContents_8);
        l_rol_up->setObjectName(QString::fromUtf8("l_rol_up"));
        l_rol_up->setGeometry(QRect(8, 140, 40, 40));
        l_rol_up->setStyleSheet(QString::fromUtf8("border-image: url(:/images/con_recong/RollerUpOn.png);"));
        l_backupdri = new QLabel(scrollAreaWidgetContents_8);
        l_backupdri->setObjectName(QString::fromUtf8("l_backupdri"));
        l_backupdri->setGeometry(QRect(170, 330, 40, 20));
        l_backupdri->setStyleSheet(QString::fromUtf8("border-image: url(:/images/con_recong/backupdriveron.png);"));
        scrollArea_7->setWidget(scrollAreaWidgetContents_8);
        scrollArea_8 = new QScrollArea(tab_2);
        scrollArea_8->setObjectName(QString::fromUtf8("scrollArea_8"));
        scrollArea_8->setGeometry(QRect(450, 10, 201, 381));
        scrollArea_8->setWidgetResizable(true);
        scrollAreaWidgetContents_7 = new QWidget();
        scrollAreaWidgetContents_7->setObjectName(QString::fromUtf8("scrollAreaWidgetContents_7"));
        scrollAreaWidgetContents_7->setGeometry(QRect(0, 0, 199, 379));
        l_rls_3 = new MQlabel(scrollAreaWidgetContents_7);
        l_rls_3->setObjectName(QString::fromUtf8("l_rls_3"));
        l_rls_3->setGeometry(QRect(160, 186, 30, 30));
        l_rls_3->setStyleSheet(QString::fromUtf8("border-image: url(:/images/warning/normal.png);"));
        l_fm_2 = new MQlabel(scrollAreaWidgetContents_7);
        l_fm_2->setObjectName(QString::fromUtf8("l_fm_2"));
        l_fm_2->setGeometry(QRect(110, 304, 30, 30));
        l_fm_2->setStyleSheet(QString::fromUtf8("border-image: url(:/images/warning/normal.png);"));
        label_45 = new QLabel(scrollAreaWidgetContents_7);
        label_45->setObjectName(QString::fromUtf8("label_45"));
        label_45->setGeometry(QRect(10, 296, 40, 40));
        label_45->setStyleSheet(QString::fromUtf8("border-image: url(:/images/parameters/FrontMotorSpeed.png);"));
        l_fas_3 = new MQlabel(scrollAreaWidgetContents_7);
        l_fas_3->setObjectName(QString::fromUtf8("l_fas_3"));
        l_fas_3->setGeometry(QRect(160, 108, 30, 30));
        l_fas_3->setStyleSheet(QString::fromUtf8("border-image: url(:/images/warning/normal.png);"));
        label_76 = new QLabel(scrollAreaWidgetContents_7);
        label_76->setObjectName(QString::fromUtf8("label_76"));
        label_76->setGeometry(QRect(8, 25, 40, 40));
        label_76->setStyleSheet(QString::fromUtf8("border-image: url(:/images/engine/ReelSpeed.png);"));
        label_71 = new QLabel(scrollAreaWidgetContents_7);
        label_71->setObjectName(QString::fromUtf8("label_71"));
        label_71->setGeometry(QRect(10, 101, 40, 40));
        label_71->setStyleSheet(QString::fromUtf8("border-image: url(:/images/engine/draught_fan.png);"));
        l_rm_1 = new MQlabel(scrollAreaWidgetContents_7);
        l_rm_1->setObjectName(QString::fromUtf8("l_rm_1"));
        l_rm_1->setGeometry(QRect(60, 343, 30, 30));
        l_rm_1->setStyleSheet(QString::fromUtf8("border-image: url(:/images/warning/normal.png);"));
        l_es_3 = new MQlabel(scrollAreaWidgetContents_7);
        l_es_3->setObjectName(QString::fromUtf8("l_es_3"));
        l_es_3->setGeometry(QRect(160, 68, 30, 30));
        l_es_3->setStyleSheet(QString::fromUtf8("border-image: url(:/images/warning/normal.png);"));
        l_fm_3 = new MQlabel(scrollAreaWidgetContents_7);
        l_fm_3->setObjectName(QString::fromUtf8("l_fm_3"));
        l_fm_3->setGeometry(QRect(160, 304, 30, 30));
        l_fm_3->setStyleSheet(QString::fromUtf8("border-image: url(:/images/warning/normal.png);"));
        l_es_1 = new MQlabel(scrollAreaWidgetContents_7);
        l_es_1->setObjectName(QString::fromUtf8("l_es_1"));
        l_es_1->setGeometry(QRect(60, 68, 30, 30));
        l_es_1->setStyleSheet(QString::fromUtf8("border-image: url(:/images/warning/normal.png);"));
        l_fcm_2 = new MQlabel(scrollAreaWidgetContents_7);
        l_fcm_2->setObjectName(QString::fromUtf8("l_fcm_2"));
        l_fcm_2->setGeometry(QRect(110, 30, 30, 30));
        l_fcm_2->setStyleSheet(QString::fromUtf8("border-image: url(:/images/warning/normal.png);"));
        l_fas_1 = new MQlabel(scrollAreaWidgetContents_7);
        l_fas_1->setObjectName(QString::fromUtf8("l_fas_1"));
        l_fas_1->setGeometry(QRect(60, 108, 30, 30));
        l_fas_1->setStyleSheet(QString::fromUtf8("border-image: url(:/images/warning/normal.png);"));
        l_fas_2 = new MQlabel(scrollAreaWidgetContents_7);
        l_fas_2->setObjectName(QString::fromUtf8("l_fas_2"));
        l_fas_2->setGeometry(QRect(110, 108, 30, 30));
        l_fas_2->setStyleSheet(QString::fromUtf8("border-image: url(:/images/warning/normal.png);"));
        l_rm_2 = new MQlabel(scrollAreaWidgetContents_7);
        l_rm_2->setObjectName(QString::fromUtf8("l_rm_2"));
        l_rm_2->setGeometry(QRect(110, 343, 30, 30));
        l_rm_2->setStyleSheet(QString::fromUtf8("border-image: url(:/images/warning/normal.png);"));
        l_rls_1 = new MQlabel(scrollAreaWidgetContents_7);
        l_rls_1->setObjectName(QString::fromUtf8("l_rls_1"));
        l_rls_1->setGeometry(QRect(60, 186, 30, 30));
        l_rls_1->setStyleSheet(QString::fromUtf8("border-image: url(:/images/warning/normal.png);"));
        label_35 = new QLabel(scrollAreaWidgetContents_7);
        label_35->setObjectName(QString::fromUtf8("label_35"));
        label_35->setGeometry(QRect(10, 178, 40, 40));
        label_35->setStyleSheet(QString::fromUtf8("border-image: url(:/images/engine/RollerSpeed.png);"));
        l_df_3 = new MQlabel(scrollAreaWidgetContents_7);
        l_df_3->setObjectName(QString::fromUtf8("l_df_3"));
        l_df_3->setGeometry(QRect(160, 266, 30, 30));
        l_df_3->setStyleSheet(QString::fromUtf8("border-image: url(:/images/warning/normal.png);"));
        label_39 = new QLabel(scrollAreaWidgetContents_7);
        label_39->setObjectName(QString::fromUtf8("label_39"));
        label_39->setGeometry(QRect(10, 258, 40, 40));
        label_39->setStyleSheet(QString::fromUtf8("border-image: url(:/images/engine/Elevator.png);"));
        label_13 = new QLabel(scrollAreaWidgetContents_7);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(110, -2, 31, 31));
        label_75 = new QLabel(scrollAreaWidgetContents_7);
        label_75->setObjectName(QString::fromUtf8("label_75"));
        label_75->setGeometry(QRect(11, 222, 35, 35));
        label_75->setStyleSheet(QString::fromUtf8("border-image: url(:/images/engine/ReThreshing.png);"));
        l_cm_2 = new MQlabel(scrollAreaWidgetContents_7);
        l_cm_2->setObjectName(QString::fromUtf8("l_cm_2"));
        l_cm_2->setGeometry(QRect(110, 226, 30, 30));
        l_cm_2->setStyleSheet(QString::fromUtf8("border-image: url(:/images/warning/normal.png);"));
        label_72 = new QLabel(scrollAreaWidgetContents_7);
        label_72->setObjectName(QString::fromUtf8("label_72"));
        label_72->setGeometry(QRect(10, 62, 40, 40));
        label_72->setStyleSheet(QString::fromUtf8("border-image: url(:/images/engine/cut_mach.png);"));
        l_df_1 = new MQlabel(scrollAreaWidgetContents_7);
        l_df_1->setObjectName(QString::fromUtf8("l_df_1"));
        l_df_1->setGeometry(QRect(60, 266, 30, 30));
        l_df_1->setStyleSheet(QString::fromUtf8("border-image: url(:/images/warning/normal.png);"));
        l_rls_2 = new MQlabel(scrollAreaWidgetContents_7);
        l_rls_2->setObjectName(QString::fromUtf8("l_rls_2"));
        l_rls_2->setGeometry(QRect(110, 186, 30, 30));
        l_rls_2->setStyleSheet(QString::fromUtf8("border-image: url(:/images/warning/normal.png);"));
        l_fcm_3 = new MQlabel(scrollAreaWidgetContents_7);
        l_fcm_3->setObjectName(QString::fromUtf8("l_fcm_3"));
        l_fcm_3->setGeometry(QRect(160, 30, 30, 30));
        l_fcm_3->setStyleSheet(QString::fromUtf8("border-image: url(:/images/warning/normal.png);"));
        l_cm_3 = new MQlabel(scrollAreaWidgetContents_7);
        l_cm_3->setObjectName(QString::fromUtf8("l_cm_3"));
        l_cm_3->setGeometry(QRect(160, 226, 30, 30));
        l_cm_3->setStyleSheet(QString::fromUtf8("border-image: url(:/images/warning/normal.png);"));
        label_70 = new QLabel(scrollAreaWidgetContents_7);
        label_70->setObjectName(QString::fromUtf8("label_70"));
        label_70->setGeometry(QRect(10, 337, 40, 40));
        label_70->setStyleSheet(QString::fromUtf8("border-image: url(:/images/parameters/RearMotorSpeed.png);"));
        l_fcm_1 = new MQlabel(scrollAreaWidgetContents_7);
        l_fcm_1->setObjectName(QString::fromUtf8("l_fcm_1"));
        l_fcm_1->setGeometry(QRect(60, 30, 30, 30));
        l_fcm_1->setStyleSheet(QString::fromUtf8("border-image: url(:/images/warning/normal.png);"));
        label_11 = new QLabel(scrollAreaWidgetContents_7);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(165, -2, 21, 31));
        label_12 = new QLabel(scrollAreaWidgetContents_7);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(60, -2, 31, 31));
        l_cm_1 = new MQlabel(scrollAreaWidgetContents_7);
        l_cm_1->setObjectName(QString::fromUtf8("l_cm_1"));
        l_cm_1->setGeometry(QRect(60, 226, 30, 30));
        l_cm_1->setStyleSheet(QString::fromUtf8("border-image: url(:/images/warning/normal.png);"));
        l_df_2 = new MQlabel(scrollAreaWidgetContents_7);
        l_df_2->setObjectName(QString::fromUtf8("l_df_2"));
        l_df_2->setGeometry(QRect(110, 266, 30, 30));
        l_df_2->setStyleSheet(QString::fromUtf8("border-image: url(:/images/warning/normal.png);"));
        l_rm_3 = new MQlabel(scrollAreaWidgetContents_7);
        l_rm_3->setObjectName(QString::fromUtf8("l_rm_3"));
        l_rm_3->setGeometry(QRect(160, 343, 30, 30));
        l_rm_3->setStyleSheet(QString::fromUtf8("border-image: url(:/images/warning/normal.png);"));
        l_es_2 = new MQlabel(scrollAreaWidgetContents_7);
        l_es_2->setObjectName(QString::fromUtf8("l_es_2"));
        l_es_2->setGeometry(QRect(110, 68, 30, 30));
        l_es_2->setStyleSheet(QString::fromUtf8("border-image: url(:/images/warning/normal.png);"));
        l_fm_1 = new MQlabel(scrollAreaWidgetContents_7);
        l_fm_1->setObjectName(QString::fromUtf8("l_fm_1"));
        l_fm_1->setGeometry(QRect(60, 304, 30, 30));
        l_fm_1->setStyleSheet(QString::fromUtf8("border-image: url(:/images/warning/normal.png);"));
        label_33 = new QLabel(scrollAreaWidgetContents_7);
        label_33->setObjectName(QString::fromUtf8("label_33"));
        label_33->setGeometry(QRect(8, 140, 40, 40));
        label_33->setStyleSheet(QString::fromUtf8("border-image: url(:/images/engine/FeedAugerSpeed.png);"));
        l_fd_2 = new MQlabel(scrollAreaWidgetContents_7);
        l_fd_2->setObjectName(QString::fromUtf8("l_fd_2"));
        l_fd_2->setGeometry(QRect(110, 147, 30, 30));
        l_fd_2->setStyleSheet(QString::fromUtf8("border-image: url(:/images/warning/normal.png);"));
        l_fd_3 = new MQlabel(scrollAreaWidgetContents_7);
        l_fd_3->setObjectName(QString::fromUtf8("l_fd_3"));
        l_fd_3->setGeometry(QRect(160, 147, 31, 31));
        l_fd_3->setStyleSheet(QString::fromUtf8("border-image: url(:/images/warning/normal.png);"));
        l_fd_1 = new MQlabel(scrollAreaWidgetContents_7);
        l_fd_1->setObjectName(QString::fromUtf8("l_fd_1"));
        l_fd_1->setGeometry(QRect(60, 147, 30, 30));
        l_fd_1->setStyleSheet(QString::fromUtf8("border-image: url(:/images/warning/normal.png);"));
        scrollArea_8->setWidget(scrollAreaWidgetContents_7);
        QIcon icon3;
        icon3.addFile(QString::fromUtf8(":/images/setdia.png"), QSize(), QIcon::Normal, QIcon::Off);
        tabWidget->addTab(tab_2, icon3, QString());
        tab_3 = new QWidget();
        tab_3->setObjectName(QString::fromUtf8("tab_3"));
        QIcon icon4;
        icon4.addFile(QString::fromUtf8(":/images/help.png"), QSize(), QIcon::Normal, QIcon::Off);
        tabWidget->addTab(tab_3, icon4, QString());
        lcdNumber = new QLCDNumber(myWidget);
        lcdNumber->setObjectName(QString::fromUtf8("lcdNumber"));
        lcdNumber->setGeometry(QRect(560, 414, 151, 35));
        QFont font3;
        font3.setPointSize(15);
        lcdNumber->setFont(font3);
        lcdNumber->setStyleSheet(QString::fromUtf8("background:blue;"));
        exit = new QPushButton(myWidget);
        exit->setObjectName(QString::fromUtf8("exit"));
        exit->setGeometry(QRect(710, 411, 91, 41));
        exit->setStyleSheet(QString::fromUtf8("border-image: url(:/images/exit.png);"));
        syssw = new QStackedWidget(myWidget);
        syssw->setObjectName(QString::fromUtf8("syssw"));
        syssw->setGeometry(QRect(0, -1, 801, 451));
        syssw->setStyleSheet(QString::fromUtf8("border-image: url(:/images/bg.png);"));
        page = new QWidget();
        page->setObjectName(QString::fromUtf8("page"));
        sbtn = new QPushButton(page);
        sbtn->setObjectName(QString::fromUtf8("sbtn"));
        sbtn->setGeometry(QRect(420, 140, 211, 100));
        QFont font4;
        font4.setFamily(QString::fromUtf8("AR PL UKai CN"));
        font4.setPointSize(20);
        sbtn->setFont(font4);
        sbtn->setStyleSheet(QString::fromUtf8("border-image: url(:/images/main.png);"));
        out_btn = new QPushButton(page);
        out_btn->setObjectName(QString::fromUtf8("out_btn"));
        out_btn->setGeometry(QRect(760, 1, 40, 40));
        out_btn->setStyleSheet(QString::fromUtf8("border-image: url(:/images/out.png);"));
        label_2 = new QLabel(page);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(200, 140, 50, 50));
        label_2->setStyleSheet(QString::fromUtf8("border-image: url(:/images/name.png);"));
        uname = new SoftKeyLineEdit(page);
        uname->setObjectName(QString::fromUtf8("uname"));
        uname->setGeometry(QRect(259, 146, 140, 40));
        uname->setStyleSheet(QString::fromUtf8("border-image: url(:/images/white.png);"));
        upassword = new SoftKeyLineEdit(page);
        upassword->setObjectName(QString::fromUtf8("upassword"));
        upassword->setGeometry(QRect(259, 200, 140, 40));
        upassword->setStyleSheet(QString::fromUtf8("border-image: url(:/images/white.png);"));
        label_6 = new QLabel(page);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(198, 194, 54, 50));
        label_6->setStyleSheet(QString::fromUtf8("border-image: url(:/images/pass.png);"));
        syssw->addWidget(page);
        syssw->raise();
        tabWidget->raise();
        exit->raise();
        lcdNumber->raise();

        retranslateUi(myWidget);

        tabWidget->setCurrentIndex(1);
        syssw->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(myWidget);
    } // setupUi

    void retranslateUi(QWidget *myWidget)
    {
        myWidget->setWindowTitle(QApplication::translate("myWidget", "\346\224\266\350\216\267\346\234\272\346\242\260\346\231\272\350\203\275\347\233\221\346\265\213\347\263\273\347\273\237", 0, QApplication::UnicodeUTF8));
        eng_chg->setText(QString());
        l_preheat->setText(QString());
        eng_gear->setText(QString());
        eng_hb->setText(QString());
        l_turn_lf->setText(QString());
        l_turn_rt->setText(QString());
        l_highlight->setText(QString());
        l_eng_fault->setText(QString());
        l_full->setText(QString());
        l_clutch_st->setText(QString());
        l_indt_lm->setText(QString());
        l_air_cln->setText(QString());
        l_oil_water->setText(QString());
        w_elevator->setText(QString());
        label_62->setText(QString());
        label_34->setText(QString());
        label_8->setText(QString());
        l_dtfan_sp->setText(QApplication::translate("myWidget", "0", 0, QApplication::UnicodeUTF8));
        w_rollerspeed->setText(QString());
        re_thr_sp->setText(QApplication::translate("myWidget", "0", 0, QApplication::UnicodeUTF8));
        w_re_thr_sp->setText(QString());
        w_cut_mach->setText(QString());
        label_63->setText(QString());
        label_31->setText(QString());
        l_fdaugersp->setText(QApplication::translate("myWidget", "0", 0, QApplication::UnicodeUTF8));
        label_27->setText(QString());
        l_reedspeed->setText(QApplication::translate("myWidget", "0", 0, QApplication::UnicodeUTF8));
        w_fdaugersp->setText(QString());
        l_rollerspeed->setText(QApplication::translate("myWidget", "0", 0, QApplication::UnicodeUTF8));
        cut_mach->setText(QApplication::translate("myWidget", "0", 0, QApplication::UnicodeUTF8));
        w_dtfan_sp->setText(QString());
        l_elevator->setText(QApplication::translate("myWidget", "0", 0, QApplication::UnicodeUTF8));
        label_9->setText(QString());
        w_reed_speed->setText(QString());
        label->setText(QApplication::translate("myWidget", "rpm", 0, QApplication::UnicodeUTF8));
        label_3->setText(QApplication::translate("myWidget", "rpm", 0, QApplication::UnicodeUTF8));
        label_4->setText(QApplication::translate("myWidget", "rpm", 0, QApplication::UnicodeUTF8));
        label_5->setText(QApplication::translate("myWidget", "rpm", 0, QApplication::UnicodeUTF8));
        label_10->setText(QApplication::translate("myWidget", "rpm", 0, QApplication::UnicodeUTF8));
        label_14->setText(QApplication::translate("myWidget", "rpm", 0, QApplication::UnicodeUTF8));
        label_15->setText(QApplication::translate("myWidget", "rpm", 0, QApplication::UnicodeUTF8));
        label_46->setText(QString());
        dr_fan_impr_rate->setText(QApplication::translate("myWidget", "0", 0, QApplication::UnicodeUTF8));
        dr_fan_rate->setText(QApplication::translate("myWidget", "0", 0, QApplication::UnicodeUTF8));
        l_crushrate->setText(QApplication::translate("myWidget", "0", 0, QApplication::UnicodeUTF8));
        label_107->setText(QString());
        label_106->setText(QString());
        label_111->setText(QString());
        drift_lose_rate->setText(QApplication::translate("myWidget", "0", 0, QApplication::UnicodeUTF8));
        impr_rate->setText(QApplication::translate("myWidget", "0", 0, QApplication::UnicodeUTF8));
        label_23->setText(QApplication::translate("myWidget", "%", 0, QApplication::UnicodeUTF8));
        label_29->setText(QApplication::translate("myWidget", "%", 0, QApplication::UnicodeUTF8));
        label_32->setText(QApplication::translate("myWidget", "%", 0, QApplication::UnicodeUTF8));
        label_41->setText(QApplication::translate("myWidget", "%", 0, QApplication::UnicodeUTF8));
        label_102->setText(QApplication::translate("myWidget", "%", 0, QApplication::UnicodeUTF8));
        label_88->setText(QApplication::translate("myWidget", "0", 0, QApplication::UnicodeUTF8));
        label_65->setText(QString());
        totle_km->setText(QApplication::translate("myWidget", "0", 0, QApplication::UnicodeUTF8));
        totle_tm->setText(QApplication::translate("myWidget", "0", 0, QApplication::UnicodeUTF8));
        totle_m->setText(QApplication::translate("myWidget", "0", 0, QApplication::UnicodeUTF8));
        label_49->setText(QApplication::translate("myWidget", "km", 0, QApplication::UnicodeUTF8));
        label_51->setText(QApplication::translate("myWidget", "h", 0, QApplication::UnicodeUTF8));
        label_52->setText(QApplication::translate("myWidget", "m", 0, QApplication::UnicodeUTF8));
        l_diplight->setText(QString());
        label_21->setText(QApplication::translate("myWidget", "KPa", 0, QApplication::UnicodeUTF8));
        label_20->setText(QString());
        l_eng_them->setText(QApplication::translate("myWidget", "  0", 0, QApplication::UnicodeUTF8));
        l_eng_sm->setText(QApplication::translate("myWidget", "  0", 0, QApplication::UnicodeUTF8));
        label_16->setText(QString());
        label_7->setText(QString());
        label_19->setText(QApplication::translate("myWidget", "%", 0, QApplication::UnicodeUTF8));
        label_22->setText(QApplication::translate("myWidget", "\342\204\203", 0, QApplication::UnicodeUTF8));
        l_voltage->setText(QApplication::translate("myWidget", "  0.0V", 0, QApplication::UnicodeUTF8));
        l_unloader->setText(QString());
        tabWidget->setTabText(tabWidget->indexOf(tab_8), QString());
        label_96->setText(QApplication::translate("myWidget", "0", 0, QApplication::UnicodeUTF8));
        label_28->setText(QString());
        label_59->setText(QString());
        profiling_height->setText(QApplication::translate("myWidget", "0", 0, QApplication::UnicodeUTF8));
        label_95->setText(QApplication::translate("myWidget", "0", 0, QApplication::UnicodeUTF8));
        reel_height->setText(QApplication::translate("myWidget", "0", 0, QApplication::UnicodeUTF8));
        label_68->setText(QString());
        reel_shift->setText(QApplication::translate("myWidget", "0", 0, QApplication::UnicodeUTF8));
        label_25->setText(QString());
        label_43->setText(QString());
        label_92->setText(QApplication::translate("myWidget", "cm", 0, QApplication::UnicodeUTF8));
        label_93->setText(QApplication::translate("myWidget", "cm", 0, QApplication::UnicodeUTF8));
        label_94->setText(QApplication::translate("myWidget", "cm", 0, QApplication::UnicodeUTF8));
        label_97->setText(QApplication::translate("myWidget", "cm", 0, QApplication::UnicodeUTF8));
        label_98->setText(QApplication::translate("myWidget", "cm", 0, QApplication::UnicodeUTF8));
        roller_torque->setText(QApplication::translate("myWidget", "0", 0, QApplication::UnicodeUTF8));
        l_fan_angle->setText(QApplication::translate("myWidget", "0", 0, QApplication::UnicodeUTF8));
        label_54->setText(QApplication::translate("myWidget", "0", 0, QApplication::UnicodeUTF8));
        front_motor_sp->setText(QApplication::translate("myWidget", "0", 0, QApplication::UnicodeUTF8));
        rear_motor_sp->setText(QApplication::translate("myWidget", "0", 0, QApplication::UnicodeUTF8));
        label_64->setText(QString());
        label_66->setText(QString());
        label_67->setText(QString());
        label_44->setText(QString());
        label_50->setText(QString());
        w_front_motor_sp->setText(QString());
        w_rear_motor_sp->setText(QString());
        label_83->setText(QApplication::translate("myWidget", "N\302\267m", 0, QApplication::UnicodeUTF8));
        label_84->setText(QApplication::translate("myWidget", "\302\260", 0, QApplication::UnicodeUTF8));
        label_86->setText(QApplication::translate("myWidget", "\302\260", 0, QApplication::UnicodeUTF8));
        label_87->setText(QApplication::translate("myWidget", "rpm", 0, QApplication::UnicodeUTF8));
        label_89->setText(QApplication::translate("myWidget", "rpm", 0, QApplication::UnicodeUTF8));
        label_61->setText(QApplication::translate("myWidget", "0", 0, QApplication::UnicodeUTF8));
        label_56->setText(QString());
        label_18->setText(QString());
        label_60->setText(QApplication::translate("myWidget", "0", 0, QApplication::UnicodeUTF8));
        label_40->setText(QApplication::translate("myWidget", "0", 0, QApplication::UnicodeUTF8));
        label_17->setText(QString());
        label_58->setText(QApplication::translate("myWidget", "0", 0, QApplication::UnicodeUTF8));
        label_24->setText(QString());
        label_38->setText(QString());
        l_concavecl->setText(QApplication::translate("myWidget", "0", 0, QApplication::UnicodeUTF8));
        label_57->setText(QString());
        label_30->setText(QApplication::translate("myWidget", "0", 0, QApplication::UnicodeUTF8));
        label_73->setText(QApplication::translate("myWidget", "mm", 0, QApplication::UnicodeUTF8));
        label_74->setText(QApplication::translate("myWidget", "mm", 0, QApplication::UnicodeUTF8));
        label_77->setText(QApplication::translate("myWidget", "mm", 0, QApplication::UnicodeUTF8));
        label_78->setText(QApplication::translate("myWidget", "mm", 0, QApplication::UnicodeUTF8));
        label_79->setText(QApplication::translate("myWidget", "mm", 0, QApplication::UnicodeUTF8));
        label_80->setText(QApplication::translate("myWidget", "mm", 0, QApplication::UnicodeUTF8));
        weight_wet->setText(QApplication::translate("myWidget", "0", 0, QApplication::UnicodeUTF8));
        label_36->setText(QString());
        weight_dry->setText(QApplication::translate("myWidget", "0", 0, QApplication::UnicodeUTF8));
        label_37->setText(QString());
        label_81->setText(QApplication::translate("myWidget", "kg", 0, QApplication::UnicodeUTF8));
        label_82->setText(QApplication::translate("myWidget", "kg", 0, QApplication::UnicodeUTF8));
        water_rate->setText(QApplication::translate("myWidget", "0", 0, QApplication::UnicodeUTF8));
        label_55->setText(QString());
        grain_quality_monitor->setText(QApplication::translate("myWidget", "0", 0, QApplication::UnicodeUTF8));
        label_26->setText(QString());
        label_100->setText(QApplication::translate("myWidget", "kg", 0, QApplication::UnicodeUTF8));
        label_101->setText(QApplication::translate("myWidget", "%", 0, QApplication::UnicodeUTF8));
        label_99->setText(QApplication::translate("myWidget", "0", 0, QApplication::UnicodeUTF8));
        label_85->setText(QApplication::translate("myWidget", "0", 0, QApplication::UnicodeUTF8));
        label_42->setText(QString());
        label_69->setText(QString());
        label_90->setText(QApplication::translate("myWidget", "kg/\343\216\241", 0, QApplication::UnicodeUTF8));
        label_91->setText(QApplication::translate("myWidget", "kg/s", 0, QApplication::UnicodeUTF8));
        control_set->setText(QApplication::translate("myWidget", "\344\273\252\350\241\250\n"
"\346\216\247\345\210\266", 0, QApplication::UnicodeUTF8));
        parameter_set->setText(QApplication::translate("myWidget", "\345\217\202\346\225\260\n"
"\350\256\276\347\275\256", 0, QApplication::UnicodeUTF8));
        parameter_set_2->setText(QApplication::translate("myWidget", "\345\217\202\346\225\260\n"
"\346\240\207\345\256\232", 0, QApplication::UnicodeUTF8));
        label_47->setText(QApplication::translate("myWidget", "0", 0, QApplication::UnicodeUTF8));
        label_48->setText(QApplication::translate("myWidget", "Hz", 0, QApplication::UnicodeUTF8));
        label_112->setText(QString());
        tabWidget->setTabText(tabWidget->indexOf(tab), QString());
        l_cuthei_down->setText(QString());
        l_reelval_down->setText(QString());
        l_reel_down->setText(QString());
        l_clusterval_off->setText(QString());
        s_minus->setText(QString());
        l_cluster_off->setText(QString());
        s_plus->setText(QString());
        l_clusterval_on->setText(QString());
        l_unswout->setText(QString());
        l_unswin->setText(QString());
        l_reelval_up->setText(QString());
        s_fan->setText(QString());
        l_reel_up->setText(QString());
        l_unswinval->setText(QString());
        l_cuthei_up->setText(QString());
        l_unswoutval->setText(QString());
        l_rolval_down->setText(QString());
        l_cutheival_down->setText(QString());
        l_cutheival_up->setText(QString());
        l_rolval_up->setText(QString());
        l_cluster_on->setText(QString());
        l_rol_down->setText(QString());
        l_rol_up->setText(QString());
        l_backupdri->setText(QString());
        l_rls_3->setText(QString());
        l_fm_2->setText(QString());
        label_45->setText(QString());
        l_fas_3->setText(QString());
        label_76->setText(QString());
        label_71->setText(QString());
        l_rm_1->setText(QString());
        l_es_3->setText(QString());
        l_fm_3->setText(QString());
        l_es_1->setText(QString());
        l_fcm_2->setText(QString());
        l_fas_1->setText(QString());
        l_fas_2->setText(QString());
        l_rm_2->setText(QString());
        l_rls_1->setText(QString());
        label_35->setText(QString());
        l_df_3->setText(QString());
        label_39->setText(QString());
        label_13->setText(QApplication::translate("myWidget", "HS", 0, QApplication::UnicodeUTF8));
        label_75->setText(QString());
        l_cm_2->setText(QString());
        label_72->setText(QString());
        l_df_1->setText(QString());
        l_rls_2->setText(QString());
        l_fcm_3->setText(QString());
        l_cm_3->setText(QString());
        label_70->setText(QString());
        l_fcm_1->setText(QString());
        label_11->setText(QApplication::translate("myWidget", "B", 0, QApplication::UnicodeUTF8));
        label_12->setText(QApplication::translate("myWidget", "LS", 0, QApplication::UnicodeUTF8));
        l_cm_1->setText(QString());
        l_df_2->setText(QString());
        l_rm_3->setText(QString());
        l_es_2->setText(QString());
        l_fm_1->setText(QString());
        label_33->setText(QString());
        l_fd_2->setText(QString());
        l_fd_3->setText(QString());
        l_fd_1->setText(QString());
        tabWidget->setTabText(tabWidget->indexOf(tab_2), QString());
        tabWidget->setTabText(tabWidget->indexOf(tab_3), QString());
        exit->setText(QString());
        sbtn->setText(QString());
        out_btn->setText(QString());
        label_2->setText(QString());
        label_6->setText(QString());
    } // retranslateUi

};

namespace Ui {
    class myWidget: public Ui_myWidget {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MYWIDGET_H
